image: "python:3.7"

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - pip install -r requirements.txt
  script:
    - ./tests/default/build.bash
  artifacts:
    paths:
      - ./tests/default/output/
      - ./tests/default/debug.log

test:
  stage: test
  before_script:
    # NOTE: This attempts to avoid knowing the 'project_slug' for project
    - cd ./tests/default/output/*
  script:
    - ./script/tests
  dependencies:
    - build
