#!/bin/sh
# vim: set ts=4:
#
# Runs linters, tests etc.
#
# This script follows convention https://github.com/github/scripts-to-rule-them-all.
set -u

. "$(dirname "$0")/bootstrap"

info 'Running tests...'
pytest  test/

info 'Building documentation...'
sphinx-build -b html doc doc/_build/html
